### ISSUE TITLE
Eject from CRA

### ISSUE THREAD

**Issue by mattgrill** [jsdrupal/drupal-admin-ui#1]
Can we `eject` from CRA and use the defaults it provides? I think long term we'll probably run into some configuration we need/want to change and that might be difficult. 

I personally don't mind setting up and maintaining the build process, if thats something that is worrisome.

**Comment by dawehner** [comment]
I'm curious whether we should wait till we need it?

**Comment by ApacheEx** [comment]
Hi guys,
There is no way to back if you `eject`. I think it's better to wait till it's really needed.
CRA is already the best way to create a react based project.
As I know there will be a release of 2.0 (soon) which has many improvements and features (of course without any breaking changes).

**Comment by mattgrill** [comment]
> There is no way to back if you eject (I'd not recommend it).

You can always copy your components to a new CRA project, and move from there. I'm sure that CRA is great if you just want to get started quickly, and don't have the time or the interest in setting up the build tools.

@dawehner I mean, no one has worked on this except for committing the CRA scaffolding, so why not now?

**Comment by dawehner** [comment]
I have a branch for example

**Comment by justafish** [comment]
I strongly agree that we shouldn't eject unless we absolutely have to. It's been really successful for me on long-term projects.

**Comment by dawehner** [comment]
I had great experience with using CRA and shitty experience with trying to move back into a custom config. I fear we need to do custom stuff, but I kinda thing we should worry about that, when its time for it.
