### ISSUE TITLE
Come up with an agenda/attendee list for JS sprint at Front End United

### ISSUE THREAD

**Issue by webchick** [jsdrupal/drupal-admin-ui#105]
Based on discussions w/ core committers, it seems like it would be very advantageous to get everyone on the same page about what this initiative is attempting to do, plans on how/when exactly to get the work into core, how to handle major points of collaboration, work through some architectural questions, etc.

[Front End United](https://www.frontendunited.org/) is coming up the weekend of Thursday, May 31 - Saturday, June 2, and has [sprinting space available](https://www.frontendunited.org/program/coworking-code-sprints) the weekdays prior (Monday, May 28 - Wednesday, May 30). Several key initiative folks are already planning to be there, along with committers such as Dries and Alex Pott.

So let's figure out:

1. What's the agenda for such a sprint?
2. Who's coming and when can they be there? (and/or participate remotely)

Here's a stab. I'm sure it needs lots of work.

## Logistics
Sprint runs Tuesday, May 29 until Friday, May 1.
Location is at the co-working code sprints at Front End United in Utrecht, Netherlands: https://www.frontendunited.org/program/coworking-code-sprints
Address:
In de Ruimte
Oudegracht-Tolsteegzijde 230, 3511 NT Utrecht

~~Cost is €11.95 / day; tickets available at https://www.eventbrite.com/e/frontend-united-utrecht-tickets-40107668115~~ Apparently we are getting access to the space for free! :O Thanks, FEU! :D

## Agenda

* Agreement on scope/timeline for initiative w/ Dries + other committers
* Work through architectural questions of various issues tagged [Problems That Need Solving](https://github.com/jsdrupal/drupal-admin-ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22Problems+That+Need+Solving+%F0%9F%A4%94%22), ideally with outside expertise:
  * Views support / What should "site builders" be able to change: #15 
  * What should themes be able to alter: #14 
  * What should modules be able to alter: #13
  * Translation/localization: #11
  * Component library: #17
  * Routing: #12 
 * Dynamic loading of additional JS from modules?
* Hammer out plan for release management challenges:
  * Experimental vs. Stable
  * GitHub ❤️ 
  * Coordination with API-First initiative
* Next-generation admin UI designs, goals, and how to integrate with them.
  * Ideally we would be able to come up with tasks for people to get involved
* Flesh out roadmap for admin UI: release 1, release 2, release 3... and how/when to integrate upstream with Drupal.

(This seems like a VERY lofty list, so we probably want to prioritize it and focus on doing only a few of these things well.)

## Who/when?
If you're planning to attend (remotely or in-person), please fill out your availability at https://docs.google.com/spreadsheets/d/1b73QHyqRKzbiL_sdAflnBCGLbLOghhdTq4VjnyQq7_0/edit?ts=5a9f9ba3#gid=0 under the "Drupal JavaScript Initiative / Admin UI" heading (~row 125).

## FAQ

Do I need to buy a ticket for the conference?

> webchick 
> @dawehner I looked into that, and no. However, you *do* need to buy daily tickets to the co-working space. Sec.
>
> https://www.frontendunited.org/program/coworking-code-sprints

**Comment by justafish** [comment]
🎉

regarding `$someone from React/Gutenberg` - rendering a thing in React is, ironically, the absolute least of our challenges 😂People doing day-in-day-out client work with CMSes would be more valuable imo

**Comment by ol0lll** [comment]
I would like to join.

| Name | Role | Dates |
| :--: | :--: | :--: |
| Volker Killesreiter  |  Developer for the thunder core team (thunder_admin theme maintainer)  |  May 28 afternoon-June 2 |

**Comment by justafish** [comment]
Could everyone please add their availability to these spreadsheet? We're under "Drupal JavaScript Initiative / Admin UI	" https://docs.google.com/spreadsheets/d/1b73QHyqRKzbiL_sdAflnBCGLbLOghhdTq4VjnyQq7_0/edit?ts=5a9f9ba3#gid=0

Thanks!

**Comment by justafish** [comment]
FYI attendees: Frontend United will be making the sprint free and tickets for the co-working space won't be required 🎉

**Comment by BarisW** [comment]
Also, we planned a social event every night of the week, with limited availability. Please book your spot ASAP: https://www.frontendunited.org/social-track

**Comment by webchick** [comment]
Wow, that's SO awesome! Thank you, Frontend United! :D

On Monday's call we got clarity around the dates of the sprint, the attendees of the sprint, and their general availability, which is a huge step (updated the summary with that info).

One thing we don't yet have clarity around though is an "agenda" of what we're hoping to accomplish. This is helpful not only for having alignment going into things, but also for people who want to participate remotely to know where they can jump in.

Right now, the proposed agenda is kind of a grab-bag of various things we "could" talk about, from broader roadmap/milestone/alignment stuff, to really digging into the proposed admin UI redesign and how to map that to this initiative, to gnarly architectural things. I would *really* like to cull that list down, ideally to maybe 3 main things (which would be one for each day + a day for overflow/parking lot), with a shared "deliverable" goal at the end. For example, a more detailed roadmap mapped against proposed milestones + dates that's signed off on by those in attendance, or a working prototype of the react admin UI handling translations + views and using the new UI style, or so on. And let everything we talk about fall under that.

Because otherwise, one of the big concerns I have is that _all of those things are important_, and _all of them are really fucking hard_. Meaning I could easily see that we spend a full day and a half of our 4 days talking about *just* the Views issue, while Cristina with her new admin UI designs twiddles her thumbs in the corner, or whatever.

We have a core committer meeting on Thursday morning (Pacific) which would be an ideal place to share such a proposed agenda, to get outside feedback that the issues we're planning to work on sound like the right ones. That timeline would also give us the opportunity to get a quick announcement out about the sprint, including what days we're planning on talking about what, so that remote folks could make time to attend.

So. Thoughts?

**Comment by dawehner** [comment]
+1 on an agenda. It certainly helps to not go off the rails and do something completely different, even we might not be able to go through all the points.

* I generalized some of the issues (form api / themeable output to describe that it is actually about)
* Replaced challenges with questions. Challenges exist when you know what you want to build, but [IMHO](https://xkcd.com/1989/) that's requires these questions to be answered
* There was not a single emoji in the agenda yet, so I replaced github with github <3 :)
* Added a point on the admin UI design, to define tasks
* > (This seems like a VERY lofty list, so we probably want to prioritize it and focus on doing only a few of these things well.)

  From my perspective all depends on these questions. "Build the admin UI using JS to improve the UX" is a really loose definition. Once we have answers to these questions I think things like 
> * Flesh out roadmap for admin UI: release 1, release 2, release 3... and how/when to integrate upstream with Drupal.

 would actually be doable.
  
* One question which [IMHO](https://xkcd.com/1989/) would be interesting to ask: Are we focusing on the content authors, site builders or both. Are the site builder problems tasks we can actually solve in a reasonable release cycle and solve us some of the problems, so the content author scope could be smaller afterwards?

**Comment by dawehner** [comment]
One thing which might be worth making clear. As long there are mockups/designs we can continue building. As we go we can add extension points, but I think talking about some of those fundamental questions in parallel is an important step.

**Comment by webchick** [comment]
Feedback from the core committers:

- Primary goal: Update the roadmap to reflect the current state of the initiative, including priorities/milestones (e.g. this by 8.6, this by 8.7).
- Rather than should we / how can we support translation... e.g. focus on "when" in the roadmap can we be tackling translation?
- Important to define the "scope" of the support of these items. (At this phase, zero views support, at this phase this minimal support, and this phase this expanded support.)
- Dig into architectural problems enough to understand the problem space, what the various parts are, and get at loose estimates of how long it takes. And focus roadmap around parts (Defined not as "20% support" of views, but "this, and this, and this sub-feature.")

**Comment by dawehner** [comment]
I totally understand the need to be able to plan ahead. For me the scope, especially in the full context of Drupal, is just too massive: Hey here build this awesome new skyscraper, but our architect just started and has like 10 other projects to work on first.
Can you give us the cost? :)

An alternative to help estimating projects and actually getting things done is to make the scope smaller. There could be various ways:

* Focus on less than EVERYTHING. For example we could focus for 8.7 to build a nice field UI and reusable form components and in 8.8 to build a nice content add/editing UI using these nice reusable components. 
* We don't care about extensiblity: I think initially building a UI without any, but discussing the extension point is one approach. We could say: Our goal for 8.7 is no extensibility and for 8.8 some level, based upon common needs.

Is this some answer to your question?

As far as I understand the point the committers try to make is: Have a plan to stay in focus?

@webchick Would there be a way to potentially get rid of having a proxy for every conversations of this kind? I do understand the need sometimes, but it feels like it is the default. Don't we have the weekly meethings for exactly this?

> Primary goal: Update the roadmap to reflect the current state of the initiative, including priorities/milestones (e.g. this by 8.6, this by 8.7).
Didn't we wrote https://www.drupal.org/project/drupal/issues/2926656 not too long ago?

**Comment by ckrina** [comment]
@dawehner we're working with the idea of the content authors as the main ones, but we can go deeper into that in a meeting or in the sprints.

What would be useful for us to be decided at FU:
For the “Eight” theme:
- Will it be used as fallback for React UI?
- Deadlines: when it needs to be done and when it's too late to invest more time on that
For Design:
- Define which components are the most needed for MVP
For UX study:
- Deadlines and milestones to get results for

**Comment by yoroy** [comment]
Maybe the items in the agenda were not sorted yet? That first "Agreement on scope/timeline for initiative w/ Dries + other committers", I would think is the intended outcome of the multiple discussions we need to have.
