### ISSUE TITLE
composer create-project fails for Node 10

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#108]
When I follow the step on the main page, namely

composer create-project jsdrupal/drupal-admin-ui-demo -s dev --prefer-dist

After a time I get this response.

....

 - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing asm89/stack-cors (1.2.0): Loading from cache
  - Installing drupal/core (8.6.x-dev dc4fa9e): Loading from cache
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2018-04-11/2911319-2-191.patch (Provide a single command to install & run Drupal)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-04-11/2911319-2-191.patch

  - Installing drupal/jsonapi (1.15.0): Loading from cache

.....

So it looks like D8.6.x has been updated past the point at which 2018-04-11/2911319-2-191.patch is usable. And the patch needs a reroll

**Comment by martinfrances107** [comment]
I was on Node 10 ... downgrading to node 9.11.1 solves the problem

The GitHub summary says Node 8 is required ... so I think that need to be changes to a range.

**Comment by dawehner** [comment]
That's quite interesting. I just tried to reproduce this problem. Node 10 just worked. Maybe this was a temporary hickup due to the patch not longer being required.

**Comment by martinfrances107** [comment]
Thanks for taking a look at this .... I am glad it can in principle be made to work.

To see if it was a hickup  --  I deleted my drupal-admin-ui directory and started from new -  following the  install  the steps in README... this time through I got a little further but failed.

The composer create-project returned without errors ... 

This time things failed on the devify steps... I am posting the full response below.

 but it looks like **upath** and **node** have compatibility issues 

`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

Maybe upath the thing unique to my machine ... I will investigate further 

Here is the full command and response.

` composer run-script devify
`

```
A script named install would override a Composer command and has been skipped
> git clone https://github.com/jsdrupal/drupal-admin-ui
Cloning into 'drupal-admin-ui'...
> cp drupal-admin-ui/.env drupal-admin-ui/.env.local
> cd drupal-admin-ui && yarn install
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:15326) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Script cd drupal-admin-ui && yarn install handling the devify event returned with error code 1

```

**Comment by martinfrances107** [comment]
Just making notes for myself ..Changes I have made without success.

I was on node 10.5.0 ... I upgraded to 10.6.0 

I did have a package in yarn global .. I removed it just in case it was holding back the installed version of upath... no change.

I have not reported my version of yarn yet... 1.7.0

**Comment by dawehner** [comment]
@martinfrances107 So the issue is resolved for you?

**Comment by martinfrances107** [comment]
No, I am still having to downgrade to node 9 to make progress elsewhere.

BUT

A) This morning I am more convinced it is a local screw up .on my machine...

B) Regarding the "node engine" in the bug report ... when I look at the PR 

https://github.com/jsdrupal/drupal-admin-ui/pull/141/files

 in the package.json file .... the engine is locked down to node 8.11 

So I am thinking of delaying further inspection of the problem until the Nightwatch issue is committed to master.

Thanks again for paying attention ... it is much appreciated.

**Comment by martinfrances107** [comment]
I have just 

- Reverted to Node 10.6 
- Wiped away my drupal-admin-ui-demo directory 
- Followed the install procedure again

ALL is good it looks like #141 resolved the issue.

Well a large number of unmet dependancy warning messages just started to appear
BUT I am going to file another issue for that.

So now that two people have reported success  on Node 10 there is just one seemingly  ultra trivial step 

 to update the readme..  to add "OR GREATER" to this sentence

**Developing** 
Ensure you have Node 8 or greater  and Yarn installed.

I will file a PR this weekend.
