### ISSUE TITLE
Allow sorting content by table column

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#120]
The current admin content table allows sorting by a table columns. This seems useful so we probably want to include this in our demo.

![screen shot 2018-06-06 at 15 59 07](https://user-images.githubusercontent.com/1845495/41027996-a0d98866-69a2-11e8-855f-199c3583edb1.png)

**Comment by dawehner** [comment]
In case you tackle this issue. The sorting should be handled by adapting the resulting query, not by sorting the data we have.
