### ISSUE TITLE
Add support for adding new content with the 'plus' button.

### ISSUE THREAD

**Issue by mattgrill** [jsdrupal/drupal-admin-ui#152]
The plus button currently does not offer the same functionality that `/node/add` normally would.

- all content types are currently loaded for the content listing page. 

<img width="221" alt="react_app" src="https://user-images.githubusercontent.com/1090713/42275683-090c7ad2-7f89-11e8-9b04-131de2e5daca.png">

**Comment by lauriii** [comment]
This is fixed by #159
