### ISSUE TITLE
options_select field widget

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#154]
Similar to https://github.com/jsdrupal/drupal-admin-ui/pull/148/files#diff-4ed0700d6e4aa3489751ab950e7bbe5a we should have a select widget ```\Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsSelectWidget```

I suppose we will need some level of settings of the allowed values, which probably should be exposed as part of the schema. This might be a tricky issue ...

**Comment by VD39** [comment]
I will take this issue.
