### ISSUE TITLE
Entity reference field widget

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#155]
We need some entity reference field widgets for

* Referencing users
* Referencing taxonomy terms, creating tags

There is https://material-ui.com/demos/autocomplete/#autocomplete available, but it wraps other libraries. It would be nice to look at those libraries and see whether they allow to create new tags as well.

* Creating tags might be also tricky as the API might not support it yet directly.

An additional widget is available on https://github.com/jsdrupal/drupal-admin-ui/pull/148/files#diff-4ed0700d6e4aa3489751ab950e7bbe5a

**Comment by francescopersico** [comment]
I 'll work on the issue.
