### ISSUE TITLE
Checkbox field widget

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#156]
For the "Published" checkbox we need a checkbox field widget, see ```core/lib/Drupal/Core/Field/Plugin/Field/FieldWidget/BooleanCheckboxWidget.php:20``` and https://github.com/jsdrupal/drupal-admin-ui/pull/148/files#diff-4ed0700d6e4aa3489751ab950e7bbe5a

**Comment by VD39** [comment]
I will work on this issue.

**Comment by rsanzante** [comment]
Sorry, I didn't post I was facing it.

**Comment by VD39** [comment]
As this has been merged, I assume this issue can now be closed?

**Comment by dawehner** [comment]
Totally!
