### ISSUE TITLE
Date selection field widget

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#157]
Just like ```core/lib/Drupal/Core/Datetime/Plugin/Field/FieldWidget/TimestampDatetimeWidget.php:25``` we need a widget for timestamps

Right now the UI looks like this in Drupal 
![screen shot 2018-07-04 at 14 57 01](https://user-images.githubusercontent.com/29678/42281123-89a7f714-7f9a-11e8-91f9-2dc3cfadba3f.jpg)

There is a material UI component, see https://material-ui.com/demos/pickers/ we could use

**Comment by VD39** [comment]
I will work on this issue.

**Comment by dawehner** [comment]
This is done now!
