### ISSUE TITLE
Field widgets

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#158]
For a new node form we need a couple of field widgets, which will be part of this epic.

If you are working on a field widget please assign yourself and issue and mention it in #javascript in Slack :)

**Comment by martinfrances107** [comment]
I have a comment, I hope I am not treading on anyones toes 

I am playing with code fragments trying to establish a a resuable pattern for Widgets 

here is a code snippet from 

https://material-ui.com/demos/selects/

It shows how to added labels, for selected 

`       <FormControl className={classes.formControl}>
          <InputLabel htmlFor="select-multiple-chip">Chip</InputLabel>
          <Select
            multiple
            value={this.state.name}
            onChange={this.handleChange}
            input={<Input id="select-multiple-chip" />}
            renderValue={selected => (
              <div className={classes.chips}>
                {selected.map(value => <Chip key={value} label={value} className={classes.chip} />)}
              </div>
            )}` 

Here is a different pattern for wrapping checkboxes in labels 

`      <FormControlLabel
        control={
          <Checkbox
            {...checkboxProps}
            checked={this.state.checked}
            onChange={onChange}
            value=""
          />
        }
        label={label}
      />`

I am just trying to be helpful ... about reusability .. I am just thinking out loud ... if all widgets have a label .. then maybe the label needs to be one level up and auto-added in the loop which constructs the form?

This maybe too clever, it maybe normal that labels need widget specific  theming. I will think more about this over the weekend and contribute if can .

Then there is the fact that the field can be multivalued... hmm

**Comment by dawehner** [comment]
```I am just trying to be helpful ... about reusability .. I am just thinking out loud ... if all widgets have a label .. then maybe the label needs to be one level up and auto-added in the loop which constructs the form?

```
I guess this depends on the design. There could be easily widgets with different levels of requirements where to place the label. Thoughts?

**Comment by dawehner** [comment]
We've implemented all the basic widgets. Thank you for everyone involved!
