### ISSUE TITLE
Import Proptype from 'prop-types' instead of destructing

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#160]
See conversation at https://github.com/jsdrupal/drupal-admin-ui/pull/134#discussion_r200188457

* Convert all the proptypes to use ```Proptype.string``` etc.

**Comment by rsanzante** [comment]
I understand is something like this: https://github.com/rsanzante/drupal-admin-ui/commit/e61cbaf172b6eb1d1308fcecbaf231a1e68e18be

**Comment by dawehner** [comment]
Yes, exactly!
