### ISSUE TITLE
Give all atoms a story book page

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#186]
Story book is new (  #183 ) 

Regarding the opModalButton component I want a story book entry, if only because it documents/details to new developers how icons are expected to be added as children

I have it already to go ... I just need a issue to associate a PR with.

**Comment by martinfrances107** [comment]
I have widened this issue to cover more of what react calls  "atoms" 

I have updated the storybook page for OpsModalButton so that is now shows the button in situ... inside a Table element.

Now all elements in the widget sub directory have a storybook page.

**Comment by dawehner** [comment]
@martinfrances107 I'd recommend to not try to expand the PR but rather do one thing at a time.

**Comment by martinfrances107** [comment]
I need to find more time to work on this.. Yes OpsModalButton could be split off into a isolated PR. 

Regarding the widgets - to meet the next developers expectations, I think the next step is to have a single page for each widget and then have a "contact sheet" where all widgets are displayed all at once. 

But I have been opening issues where I see problems .. and I am now juggling too many minor issues, and so the next next step is to close the other loose ends.

**Comment by martinfrances107** [comment]
❤️

**Comment by martinfrances107** [comment]
sorry closed the wrong issue.

**Comment by martinfrances107** [comment]
Thank you ❤️
