### ISSUE TITLE
Merge the support module into this repository

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#19]
Having mulltiple repositories can be annyoing, especially when they need to be kept in sync.

Idea:

* Move https://github.com/jsdrupal/drupal-admin-ui-support into this repository
* Adapt https://github.com/jsdrupal/test-project to automatically link the module to docroot/modules

**Comment by justafish** [comment]
This has been merged in now. https://github.com/jsdrupal/drupal-admin-ui-demo/issues/2 is open to fix the setup issues over there.
