### ISSUE TITLE
Collect problems a stronger type system would have helped (Flow/Typescript)

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#190]
This issue is meant to collect bugs/issue which would have been resolved by a stronger type system

Possible examples:

* Missing parameter
* null is not a function
* A disallowed value got passed along
* An array instead of a set was used.

**Comment by martinfrances107** [comment]
A second example.

While working on the newly added EntityReferenceAutocomplete widget (https://github.com/jsdrupal/drupal-admin-ui/issues/256) I noticed a minor flaw 

The widget  property **schema** is assumed to exist without actually requiring it.

see  the use of the variable this.props.schema in the handleInputChange(event)  handler.

schema is completely missing from the propTypes definition. [ I am going to add a .isRequired in #256 ]

I accept it is a small issue ... but with flow the developer could have been warned in the IDE that the property was missing.

**Comment by martinfrances107** [comment]
Thank you.  I think this issue has served its purpose.... 

We have the ability to lint and compile typescript in the master branch 

So just a little housekeeping ... I think this issue can be closed.

**Comment by dawehner** [comment]
Indeed :)
