### ISSUE TITLE
Track nightwatch failures

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#191]
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2667
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2683
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2685
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2734
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2725
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2740
* https://circleci.com/gh/jsdrupal/drupal-admin-ui/2745

**Comment by martinfrances107** [comment]
Here is a second failure.

https://circleci.com/gh/jsdrupal/drupal-admin-ui/2685

**Comment by martinfrances107** [comment]
https://circleci.com/gh/jsdrupal/drupal-admin-ui/2683

**Comment by martinfrances107** [comment]
Another random fail

https://circleci.com/gh/jsdrupal/drupal-admin-ui/2725?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

#198

**Comment by martinfrances107** [comment]
https://circleci.com/gh/jsdrupal/drupal-admin-ui/2740?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Another fail.

**Comment by martinfrances107** [comment]
The failure rate is 100%

https://circleci.com/gh/jsdrupal/drupal-admin-ui/2745?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dawehner** [comment]
Maybe the solution is to wait for longer?

**Comment by dawehner** [comment]
Thank you for tracking all those failures!

**Comment by martinfrances107** [comment]
I have gone back over all the failures and think this issue has been a success 

... and can be closed now

**Comment by dawehner** [comment]
Nice!
