### ISSUE TITLE
Enhancements to the file upload widget

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#193]
* [ ] Allow to click into the drag zone to upload a file, not just drag'n drop
* [ ] Allow multiple files to be uploaded at the same time

**Comment by VD39** [comment]
I will work on this.

**Comment by VD39** [comment]
@dawehner should the images also show? At the moment it shows only the name for me.

**Comment by dawehner** [comment]
That would be nice. Please ask ckristina whether there are any designs
available

**Comment by dawehner** [comment]
Yeah, thank you @VD39 !
