### ISSUE TITLE
Add the "Preparation time" and "Cooking time" widgets to the recipe form

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#194]
* [ ] Adapt drupal-admin-ui/src/components/05_pages/NodeForm/UiMetadata.js to contain both additional fields
* [ ] Adapt the number fields to have support for some suffix/prefix, see screenshot:

![image](https://user-images.githubusercontent.com/29678/42526373-85d4ba64-846d-11e8-91cb-5c8a00050259.png)
  Put this additional information also into the UiMetadata for the two fields.

**Comment by VD39** [comment]
I will take this.
