### ISSUE TITLE
Add a multi-delta wrapper to add the INGREDIENTS fields

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#195]
So far every field was just allowed to provide a single value. The ingredients field though can hold multiple values at once, each being a text field.

* [ ] Implement some wrapper, which allows to enter multiple data
![image](https://user-images.githubusercontent.com/29678/42526496-e1056db6-846d-11e8-975f-8287e362b504.png)
* [ ] Based upon the cardinality of the schema add the wrapper automatically to each field
* [ ] Add the ingredients field

**Comment by dawehner** [comment]
@lhuria94 I think this would work fine for a entity reference widget, but I struggling seeing how this would work for normal textfields?

Drupal has some form of strange requirements

* Some widgets handle multiple files at once (autocomplete widget, file upload)
* Some widgets don't want to handle multiple, like numbers, checkboxes, textfields etc.

It would be nice to come up with some form of abstraction which helps the second case

**Comment by lhuria94** [comment]
This example is with reference to text fields, not just for autocomplete. Like you type some text and enter, similarly, we can add multiple.

Something like this: https://material.angularjs.org/latest/demo/chips

But I see your point, guess this needs more thinking.

**Comment by VD39** [comment]
I will work on this.
