### ISSUE TITLE
Unresolvable dependencies associated with 8.7.x

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#224]
Here is a integration test failure, which is unrelated to the PR

![integrationfail](https://user-images.githubusercontent.com/1259969/43043824-8b469430-8d92-11e8-909d-feb3791c706a.png)

https://github.com/jsdrupal/drupal-admin-ui/pull/201

**Comment by dawehner** [comment]
This issue can be resolved by updating the composer lock file, so it
actually points to 8.7.x as well.

**Comment by martinfrances107** [comment]
I have seen the failing tests pass... @dawehner thanks for the prompt reply.
