### ISSUE TITLE
Ensure that all field widgets support FormControl

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#225]
The Material UI `FormControl` component can control some aspects of form elements rendered inside it: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/FormControl/FormControl.js#L138 . It seems like some, but not all of our field widgets support these configuration options.

**Comment by dawehner** [comment]
I'm a bit confused about the API exposed by material UI. Some elements, like textfield (see https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/TextField/TextField.js#L105) seem to add the form control automatically, so I guess for those we don't need to add it?

**Comment by lauriii** [comment]
In fact, `FormControl` doesn't work the way I was first expecting. I've now made sure all widgets are wrapped with `FormControl`, unless they only contain a single field that is already wrapped with `FormControl`
