### ISSUE TITLE
Enable the openapi module

### ISSUE THREAD

**Issue by VD39** [jsdrupal/drupal-admin-ui#237]
It seems the openapi module doesn't get enabled, causing an 404 API error when trying to add a recipe. 

Needs to be added here: https://github.com/jsdrupal/drupal-admin-ui/blob/master/admin_ui_support/admin_ui_support.info.yml

**Comment by dawehner** [comment]
> Needs to be added here: https://github.com/jsdrupal/drupal-admin-ui/blob/master/admin_ui_support/admin_ui_support.info.yml

+1 Do you want to create a PR for that?

**Comment by VD39** [comment]
Pull request opened. I am new this area, so I am not sure if it is correct.

**Comment by lauriii** [comment]
Good catch! This definitely is a problem. Thank you for opening the PR!

**Comment by VD39** [comment]
Closing as issue is fixed.
