### ISSUE TITLE
Update project description to make the project more discoverable.

### ISSUE THREAD

**Issue by tedbow** [jsdrupal/drupal-admin-ui#243]
Currently the project description is "v fancy ⬅️✌️➡️"

Although this description probably served it's purpose somehow I don't think this quite help newcomers actually figure what this project does 😜

Looking at the homepage for this org https://github.com/jsdrupal
![screenshot 2018-07-26 11 15 58](https://user-images.githubusercontent.com/132772/43271379-55cf1a94-90c5-11e8-8109-ecd7c56a04a0.png)

There are 2 projects pinned. I would probably investigate the other and assume this 1 was pinned by mistake.

**Comment by tedbow** [comment]
We could just take the first line of the README plus the peace wave.

> This is an admin UI for Drupal, built with JavaScript and based on create-react-app. ⬅️✌️➡️"

**Comment by mattgrill** [comment]
I just updated the description. Thanks @tedbow

**Comment by dawehner** [comment]
Good points @tedbow !

**Comment by dawehner** [comment]
Too bad we can't order them. Ideally we would put the demo first

**Comment by dawehner** [comment]
😢
