### ISSUE TITLE
Save a users in-progress node form edits which could be restored later.

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#244]
As an enhancement to show on the demo we could auto save locally all the modifications user has made on the content edit form. Then when user returns on the page, if there's a saved changes in the local storage, we could prompt the user if they would like to retrieve their previous changes.

**Comment by lauriii** [comment]
How about using snackbars to at least show a message: https://material-ui.com/demos/snackbars/

**Comment by dawehner** [comment]
Nice idea!

**Comment by dawehner** [comment]
Given we want to use redux for this piece, I think this work is blocked on https://github.com/jsdrupal/drupal-admin-ui/issues/251

**Comment by dawehner** [comment]
As first step I think it would be a bit easier to just support restoring the node add forms. The logic when to ask users to restore the node edit forms is a bit tricky, given someone else might have updated the node in the meantime.

I put some code into https://github.com/dawehner/drupal-admin-ui/tree/issue-254 but it doesn't yet cover any localStorage logic, but rather just stores and fetches node forms in redux, and then asks users to restore it.

**Comment by lauriii** [comment]
@dawehner couldn't we as a first step just store the autosave time and compare that to the entity changed time?

**Comment by dawehner** [comment]
@lauriii Sure, well all I'm saying is that you could finish add support and then do the edit support separately, which might be enough for the demo.

**Comment by lauriii** [comment]
Agreed!

**Comment by dawehner** [comment]
Unassigning myself in case someone wants to take over the edit restore logic.
