### ISSUE TITLE
WYSIWYG Field Widget

### ISSUE THREAD

**Issue by mattgrill** [jsdrupal/drupal-admin-ui#245]
Some initial research around WYSIWYG solutions. There are probably others, and some I skipped over for that that did not seem feature rich enough for our needs. 

### React Draft Wysiwyg - https://github.com/jpuri/react-draft-wysiwyg
- Support for most common elements.
- Customizable toolbar. 
- RTL and spellcheck support.
- Support for WAI-ARIA attributes.

![jpuri_react-draft-wysiwyg__a_wysiwyg_editor_build_on_top_of_reactjs_and_draftjs__https___jpuri_github_io_react-draft-wysiwyg](https://user-images.githubusercontent.com/1090713/43283651-52273c56-90ce-11e8-867a-5db5d982df4d.png)

### React Rich Text Editor - https://github.com/sstur/react-rte/
- Minimal toolbar design. 
- Easily construct toolbar configuration.
- "does not store document state in the DOM"
- Supports HTML and Markdown
- Reliable undo/redo without a large memory footprint

![sstur_react-rte__pure_react_rich_text__wysisyg__editor_based_on_draft-js_](https://user-images.githubusercontent.com/1090713/43283761-9bd43a16-90ce-11e8-9f48-58b21501feee.png)

### Medium Draft - https://github.com/brijeshb42/medium-draft
- Medium-like
- Focus on keyboard shortcuts
- Easily customizable toolbar.
- Easily support image upload.

![medium-draft](https://user-images.githubusercontent.com/1090713/43283982-45698b62-90cf-11e8-8ce6-13eca496fe65.gif)

### React TinyMCE - https://github.com/instructure-react/react-tinymce
- Looks like TinyMCE
- Poor documentation.

![react_tinymce_component](https://user-images.githubusercontent.com/1090713/43284110-ad99d1b0-90cf-11e8-8f2f-0ef4305f7f21.png)

### CKEditor React - https://github.com/ckeditor/ckeditor5-react
- Looks like CKeditor? 
- Different editor builds.
- Familiar to existing Drupal users.

**Comment by mattgrill** [comment]
### Drafttail - https://github.com/springload/draftail
- Draft.js based
- Keyboard shortcuts
- "Paste from Word"
- No build in support for **links** or **images**.
- Tested with aXe.

![springload_draftail__a_configurable_rich_text_editor_based_on_draft_js__built_for_wagtail](https://user-images.githubusercontent.com/1090713/43285531-0ef5daea-90d4-11e8-838e-15594dceeefa.png)

**Comment by dcorb** [comment]
I worked with Draft.js for couple of months. I would make a proper research before chosing this library, because it implements its own data structure https://medium.com/@rajaraodv/how-draft-js-represents-rich-text-data-eeabb5f25cf2 and DraftJS doesn’t offer any “exportToHTML”  serialization.
You rely on community efforts like
https://github.com/hubspot/draft-convert or https://github.com/jpuri/draftjs-to-html to get your HTML out 
There is much more promising https://github.com/ianstormtaylor/slate but I haven’t used it personally. It’s still marked as beta
@wimleers spent a lot of time researching wysiwyg editors when doing inline editing, and collaborating with CKeditor guys. Maybe he could have suggestions where to look (edited)
Medium

**Comment by mglaman** [comment]
I think it'd be great to use CKEditor5 and continue that collaboration. I also saw a demo of it which resembled Dropbox Paper's editor. Where you can do inline markdown editing (`##` then space makes h2, etc). And "Medium" like editing where select + hover allows formatting changes. 

There are existing bridges with that community and technology, so there are benefits I believe.

**Comment by dcorb** [comment]
@mattgrill  those 2 repos don't look well maintained to me
Another issue I experienced with DraftJS is the lack of Android support. FB is not interested to fix bugs in Android browsers https://github.com/facebook/draft-js/search?q=android&type=Issues
The situation with Android could improve.. it seems:
https://github.com/facebook/draft-js/pull/1672#issuecomment-369367386


I don't know what are the implications of choosing Draft.js for drupal-admin-ui (is this project just a demo to throw away? Or the foundation for future work?)

**Comment by dawehner** [comment]
## Slate

A customizable framework for wysiwyg ediitor independent from react (https://github.com/ianstormtaylor/slate)

It seems to have a good amount of momentum and it is designed for more usecases, especiially embedding custom objects, see https://github.com/ianstormtaylor/slate#why

**Comment by dcorb** [comment]
Gutenberg from Wordpress could be ported to Drupal ? https://testgutenberg.com/
These guys did it, and they want to talk about it in DrupalEurope https://www.drupaleurope.org/session/introducing-gutenberg-content-editor-drupal-8
