### ISSUE TITLE
FileUpload does not handle terminated uploads with grace.

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#247]
There is a minor corner case outcome which is not being trapped and handled by our code.

There are several FileUpload issues

(https://github.com/jsdrupal/drupal-admin-ui/issues/193) is adding enhancements.
(https://github.com/jsdrupal/drupal-admin-ui/issues/190) shows that flow was used to catch the bug.
(https://github.com/jsdrupal/drupal-admin-ui/issues/186) is adding a storbook page for the widget.

The bug is in the FileUpload **ondrop** handler the const **files** can be null and yet "files" is always accessed as a iterator object. ( see 190 for details ).

I don't think this is high priority, I am juggling a few more important issues -- but I intend to come back to this.

**Comment by dawehner** [comment]
Thank you for documenting processes like this. People don't do that often
enough, while it gives so much longterm benefit!
I'll review PRs as you go

**Comment by VD39** [comment]
@martinfrances107 I am working on file upload at the moment, I am done with file upload component, which support multiple, and I am now working on the widget to get it to also support multiple uploads. So I can add the error handling or would you prefer to do it once I complete issue #193?

**Comment by martinfrances107** [comment]
> So I can add the error handling or would you prefer to do it once I complete issue

@VD39 

I am struggling with time at the moment, and in addition I have a few too many issues open at the moment.

So I am easy ... with a community spirited attitude - as you post a PR over there  I will comment/review and help out where I can. Also if you choose to ignore this little bug .. I am good with that.

**Comment by dawehner** [comment]
@martinfrances107 it would be super useful if you could try it out again, once #249 is in.

**Comment by martinfrances107** [comment]
Sorry for the delayed response 

So the original problem :-

>  FileUpload ondrop handler the const files can be null and yet "files" is always accessed as a iterator object. ( see 190 for details ).

in the updated version event.dataTransfer.files is blindly passed to the function readFiles() where it hits this code.

```
  const slicedFiles: Object = Object.keys(files)
      .slice(0, 2)
      .reduce((obj, value) => {
        obj[value] = files[value];
        return obj;
      }, {});
```

when files is null javascript will throw this exception 

> Uncaught TypeError: Cannot convert undefined or null to object

So the fix appears simple -- add an "if" here and message the user that the transfer failed. 

```
  /**
   * Will get the selected file/s from the file explorer.
   * @param {Event} event
   */
  getFiles = (event) => {
    files = event.target.files
    if (files) {
      this.readFile(event.target.files);
    } else {
      // Handle file aborts.
    }
  };
```

So that is the analysis part ... I will generate a PR when I can find the time.

**Comment by martinfrances107** [comment]
Just going back to the HTML5 spec.

https://www.w3.org/TR/2011/WD-html5-20110113/dnd.html#the-datatransfer-interface

Looking at the algorithm for constructing the FileList to be associated with event.dataTransfer.files

the first step is start with a empty list.... in short null in this position  is a polyfill for older browsers 

Here is the relevant section 

> The files attribute must return a live FileList sequence consisting of File objects representing the files found by the following steps. The same object must be returned each time. Furthermore, for a given FileList object and a given underlying file, the same File object must be used each time.
> 
> Start with an empty list L.
> 
> If the DataTransfer object is no longer associated with a drag data store, the FileList is empty. Abort these steps; return the empty list L.
>
