### ISSUE TITLE
Allow editing existing content

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#251]
https://github.com/jsdrupal/drupal-admin-ui/pull/171 would enable us to save new content

Once that is in, let's try to see whether we can get editing working as well

**Comment by mattgrill** [comment]
Alright, #171 has been merged. This is unblocked now.

**Comment by dawehner** [comment]
🎆

**Comment by mattgrill** [comment]
* [ ] Posting fails right now because it sends the status field which is not allowed to be sent due to workflow moderation. Ideally the PATCH would just POST changed fields
* [ ] Ensure saving actually works

**Comment by lauriii** [comment]
https://github.com/jsdrupal/drupal-admin-ui/pull/379 fixes this 🎉
