### ISSUE TITLE
Fix gramatical mistake 

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#252]
Oh well Trump said **could** when he mean **couldn't** 

and I giggled .. Now it is my turn to say Oh good grief let the  ground swallow me up" 

When I said "The" I mean't to say "To"

And the text appears twice 

>    The get both the logger to function while still pretty printing sample code
>   in the JSX tab a toSting() method must be provided.

At the start of the sentence it should say "**To** get both"

[Me stares at the ground in shame] ... I will create a PR now...

**Comment by dawehner** [comment]
Thank you for the quick fix!
