### ISSUE TITLE
Missing downshift dependancy

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#257]
There has been a mass of commits today ... 🎉 

but I think there is a missing dependency, even after a yarn update

When I open up the new file  EntityReferenceAutocomplete.js -- I see this error in my IDE

"unable to resolve downshift" ... here

> import Downshift from 'downshift';

**Comment by mattgrill** [comment]
@martinfrances107 It should be available? https://github.com/jsdrupal/drupal-admin-ui/blob/master/package.json#L25

**Comment by mattgrill** [comment]
Also part of the `yarn.lock` - https://github.com/jsdrupal/drupal-admin-ui/blob/master/yarn.lock#L3282

**Comment by martinfrances107** [comment]
You are correct, 

Sorry to give you trouble where there is none - my IDE just did not pick up the file change.

Thanks for the quick response.

**Comment by mattgrill** [comment]
@martinfrances107 Don't even worry. :) :) :)

**Comment by dawehner** [comment]
Wouldn't it be nice if yarn could check of start whether the installed node_modules are the same as the ones registered in the lock file and otherwise ask you to do another yarn install.
