### ISSUE TITLE
Setup CI tests for the embedded Drupal module

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#26]

**Comment by dawehner** [comment]
I've started to work on that as part of https://github.com/jsdrupal/drupal-admin-ui/pull/28 but I'm a bit confused why the build command doesn't execute on CI right now.

**Comment by justafish** [comment]
@dawehner this is fixed now 👍 https://packagist.org/packages/justafish/drupal-admin-ui-support
