### ISSUE TITLE
Create a snackbar message when content got created/updated

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#265]
Once https://github.com/jsdrupal/drupal-admin-ui/pull/171 is in it would be nice to show a message to the user that the content got updated/created using https://material-ui.com/demos/snackbars/#snackbars

I think we should leverage the text from the existing PHP forms:
```
    if ($insert) {
      $this->logger('content')->notice('@type: added %title.', $context);
      $this->messenger()->addStatus($this->t('@type %title has been created.', $t_args));
    }
    else {
      $this->logger('content')->notice('@type: updated %title.', $context);
      $this->messenger()->addStatus($this->t('@type %title has been updated.', $t_args));
    }
```

**Comment by porkloin** [comment]
I have most of this working, including the following:

- a general purpose snackbar component in the `<Default />` component
- Redux action/reducer for issuing snackbar notifications to the component

However, node save operations don't seem to be working on my local with the a recent code pull (as of 4ish hours ago?) so I'm having some trouble testing issuing a snackbar message on the save operation.

Forgive me if I'm just missing some critical piece of info on how node save is working atm, but once I can get my local working I'd be happy to finish this off!

**Comment by mattgrill** [comment]
I'm pretty sure this is complete now.
