### ISSUE TITLE
Improve usability of the entity reference widget

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#266]
There's some small improvements that could be made for the entity reference widget:

- [x] The field removes the focus after key down meaning that when searching for the entity, user has to re-focus after every added character.
- [ ] Entities already referenced in the field are still visible in the search results when adding more references.
- [x] Unfiltered list of entities is shown when there's no characters entered and key down is triggered

And here's a gif demonstrating these usability problems:
![entity_reference_widget](https://user-images.githubusercontent.com/1845495/43704816-0c3206f2-998b-11e8-9e95-f75d0797c455.gif)

**Comment by dawehner** [comment]
Thank you for clearly specifying why the behaviour is a bit weird indeed right now.

Do you think this is an issue we could mark as "good first issue"?

**Comment by martinfrances107** [comment]
@lauriii  .. Hi If you think this issue is resolved, would you consider closing it?

We have 60 issues open at the moment... and I am trying to prioritize which one to go for next.

**Comment by lauriii** [comment]
One of the issues reported in this issue wasn't fixed yet. Should we open another issue for that or re-open this?
