### ISSUE TITLE
Show human readable label on OptionsSelect widget

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#274]
Currently the `OptionsSelect` widget is showing the machine name of the options on the UI. It would be a nice enhancement to show the human readable name in the UI ✨

<img width="158" alt="screen shot 2018-08-07 at 18 21 59" src="https://user-images.githubusercontent.com/1845495/43773104-ce2c5bca-9a6e-11e8-8eeb-5bd6e3d5051f.png">

<img width="202" alt="screen shot 2018-08-07 at 18 22 27" src="https://user-images.githubusercontent.com/1845495/43773125-dc88a6d8-9a6e-11e8-94e9-26bd21230d6a.png">

**Comment by mattgrill** [comment]
Alright. Had a quick look at this. It doesn't actually look like the human readable names are returned from `schemata`. Additionally, both `entity_form_display` and `field_config` do not return the human readable names.

**Comment by wimleers** [comment]
Which human readable name is not being returned by `schemata`? The label of each allowed value in the allowed value list?

Also, why is `schemata` relevant here? Wouldn't this be something one would get by reading the `field_storage_config` config entity?

---

I just created a `field_options` field on `article` `node`s with the same allowed values list as in the screenshot in the OP. `http://d8/jsonapi/field_storage_config/field_storage_config/017f2e79-ceff-472e-9c5a-606c134facc1` returns:
```
{
  "data": {
    "type": "field_storage_config--field_storage_config",
    "id": "017f2e79-ceff-472e-9c5a-606c134facc1",
    "attributes": {
      "langcode": "en",
      "status": true,
      "dependencies": {
        "module": [
          "node",
          "options"
        ]
      },
      "drupal_internal__id": "node.field_op",
      "field_name": "field_op",
      "entity_type": "node",
      "field_storage_config_type": "list_string",
      "settings": {
        "allowed_values": {
          "easy": "Easy",
          "medium": "Medium",
          "hard": "Hard"
        },
        "allowed_values_function": ""
      },
      "module": "options",
      "locked": false,
      "cardinality": 1,
      "translatable": true,
      "indexes": [],
      "persist_with_no_fields": false,
      "custom_storage": false
    },
    "links": {
      "self": "http://d8/jsonapi/field_storage_config/field_storage_config/017f2e79-ceff-472e-9c5a-606c134facc1"
    }
  },
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": "http://jsonapi.org/format/1.0/"
      }
    }
  },
  "links": {
    "self": "http://d8/jsonapi/field_storage_config/field_storage_config/017f2e79-ceff-472e-9c5a-606c134facc1"
  }
}
```

As you can see, the labels are in there.

**Comment by mattgrill** [comment]
🤦‍♂️

**Comment by dawehner** [comment]
This issue is another reason one could use for moving the UI metadata logic to PHP. https://api.drupal.org/api/drupal/core%21modules%21options%21options.module/function/options_allowed_values/8.5.x shows that this could be a dynamic function so we would need some form of dynamic endpoint anyway

**Comment by mattgrill** [comment]
I'll probably get this wrapped up today.

**Comment by mattgrill** [comment]
This is effectively complete in #336, however blocked on recent CI issues.
