### ISSUE TITLE
Entity reference widget doesn't take field cardinality limitations into account

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#282]
Currently, the entity reference widget doesn't take into account the field cardinality. The widget should support both; single value and array of values that is limited.

For example, the author field should only allow a single value:
![screen shot 2018-08-08 at 13 30 37](https://user-images.githubusercontent.com/1845495/43820208-c64dd5d6-9b0f-11e8-826e-5cc3bed24f63.png)

**Comment by VD39** [comment]
This issue may now be closed.

**Comment by dawehner** [comment]
Indeed, thank you for your PR!
