### ISSUE TITLE
FileUploadWidget: Keep Storybook in sync with component changes

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#301]
The latest commit #297 broke the storybook entry for FileUploadWidget ( multiple ) 

No biggie, just want to keep these things in sync.

I am looking at this now...

**Comment by martinfrances107** [comment]
I am about to crate a PR 

Here is the main misconception, I have unpicked 

The fileItem data structure which is passed into the FileUploadWidget

it can be a file data structure or an array of many fileItem data structures 

but the change is to recognise the fileItem data structure must carry alternative text on a per item basis.

```
<FileUploadWidget value={data: [ 
      {file:{/*data struct */}, meta: {/* data struct */}}
      {file:{/*data struct */}, meta: {/* data struct */}}
      ...
]} /> 
```

Previously the code changes allowed for only one alternative  meta text string.

Anyway I hope this description is useful in showing the problem ..

PR is coming

**Comment by dawehner** [comment]
There are basically two ways the value could look like:

### Cardinality 1
```
{{"type":"file--file","id":"0b538928-09de-438d-9f33-15e0f2c104a1","meta":{"alt":"A delicious deep layered Mediterranean quiche with basil garnish.","title":null,"width":768,"height":511}
```

### Cardinality > 1

```
[{"type":"file--file","id":"426b7e5d-19f4-423c-a40d-355cb910d5fa","meta":{"alt":"Fresh cut herbs including mint, parsley, thyme and dill","title":"","width":768,"height":512}},{"type":"file--file","id":"302a93f7-dedd-40ad-b030-31be5bdb4317","meta":{"alt":"test","title":"","width":2494,"height":1416}}]}}
```

**Comment by martinfrances107** [comment]
Thanks for helping me out with this .... it is much appreciated.

Is the data structure you have provided based on the ideal .. what is expected in core ?
Is is what should be pushed to the server as a json object.?

As a mini experiment I added this debug  so I can see the item being filtered 

here is my code snippet. [ NodeForm:render()]

```
  const items = getItemsAsArray(multiple, value.data)
    // Default schema creates stub entries, which we don't need here.
    .filter(item => {
      console.log(item);
      return item.id;
    });
  console.log('filtered');
  console.log(items);
```

Visiting the "add recipe" page and uploading  a jpg here is the data structure I see.

id: xyz
file: { id: xyz .... }
meta: { alt:'' }

so id is repeated .. and as the code stands meta is outside the file object .. not inside!

While we discuss what is the appropriate data structure I am just going to set the storybook definition to match what we have in code ... and we can alter the code to the way we like it in another issue.

Here is a image which supports my claim.
 
![addrecipebeingfiltered](https://user-images.githubusercontent.com/1259969/44032852-5a2e7d70-9f00-11e8-9155-1a37d552f2d7.png)

**Comment by dawehner** [comment]
> Is the data structure you have provided based on the ideal .. what is expected in core ?
Is is what should be pushed to the server as a json object.?
