### ISSUE TITLE
The node creation forms don't work in the bundled version of the project

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#302]
This is because we can only handle paths under `/admin`

As a quick/temporary solution, could we add a redirect into the `admin_ui_support` module which creates an alias for `/node/add/recipe` to `/admin/node/add/recipe` in Drupal ?

**Comment by dawehner** [comment]
yeah, let's copy an example in the ```routing.yml``` file and use it for the recipe form. I guess we could start to just overwrite ```node/add/recipe```

**Comment by martinfrances107** [comment]
Just a little housekeeping ... can this issue be closed?

**Comment by lauriii** [comment]
This was fixed by #314
