### ISSUE TITLE
Notify user when content has been successfully created

### ISSUE THREAD

**Issue by mortenson** [jsdrupal/drupal-admin-ui#303]
When you submit a node form, there should be some kind of notification or success message when the form submission succeeds. I was thinking a redirect to `/admin/content` with a link to view the node in Drupal (its canonical route) would be a good start.

**Comment by dawehner** [comment]
Are you sure there isn't an issue for that already?

**Comment by mortenson** [comment]
@dawehner I could add this as a comment in #276? Not sure.

**Comment by lauriii** [comment]
I think this is duplicate to https://github.com/jsdrupal/drupal-admin-ui/issues/265

**Comment by mortenson** [comment]
Looks like it!
