### ISSUE TITLE
NodeForm: warns about initialization.

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#319]
When I visit 

http://localhost:3000/node/add/recipe

I see this warning in the Chrome's devtool console output.

> Warning: NodeForm: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.

We are relying on the default constructor, and have a getDerivedStateFromProps() method.

I think we need either a static state variable, or a explicit constructor 

I see a separate small blemish, in NodeForm

`static getDerivedStateFromProps(props, prevState) 
`
 makes use of props.entity -- props a function input not the class variable  this.props

Formally  entity is a implied, undeclared property. -- this code is a work in progress
and this.props.entity is a variable which is written to but never used.

I will try and make this better.

**Comment by dawehner** [comment]
This is resolved now, 🎆
