### ISSUE TITLE
EntityReferenceAutocomplete: broken accessibility

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#324]
Looking at 

localhost:9000/http://localhost:3000/node/add/recipe

I see a accessibility bug when running chrome's lighthouse test suite.

Hardcoded into EntityReferenceAutocomplete is the use of a constant id [ the id is fed in as part of a call to this.renderInput() ]

`<Textfield id = "integration-downshift-multiple" />`

This is bad in general but specifically in the case of the add recipe form as the id is repeated, once for each of the fields 

author, category, tags and 'authored by'

This breaks accessibility.  As a  labelfor property with this id is used to semantically link the INPUT element to its associated LABEL element . The same id repeated four times is unacceptable to screen readers.

This fix is simple -- we just need to add a unique 'key' variable to the id assignment.

**Comment by rahulsavaria** [comment]
Hi @lauriii,

I would like to work on this issue, can you please assign it to me.

Thanks

**Comment by dawehner** [comment]
@rahulsavaria Note: This issue is resolved already :)
