### ISSUE TITLE
add/recipe -- Border crash

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#327]
#326 has just landed and has improved the layout. 🎂 

After... I find I am still able the break the design.

On a desktop when I drag the width from maximum to small ... I find the second column text at a certain point can be made to crash into the right hand border wall.
 In the image below the d of promoted and published is affected.

![margincrash](https://user-images.githubusercontent.com/1259969/44100726-95aee69a-9fdd-11e8-94e4-3bd7c73a3762.png)

**Comment by lauriii** [comment]
We are not really focusing on the mobile experience yet since the admin UI is mainly used on desktop and it is also most important for our demo. Once we have the final designs ready, we will start focusing on the mobile and other narrow screens.

**Comment by martinfrances107** [comment]
@lauriii .. No problem. I am just dumping my personal todo list onto the public issue tracker..

I am munching my way through the issues I create.... just slowly.

**Comment by martinfrances107** [comment]
The way to fix this involves making decision about the css grid layout or using flex...

My way of rephrasing @lauriii is that this is best left for another theme/layout initiative - which is will happily participate --
