### ISSUE TITLE
FileUploadWidget: Invalid prop definition for multiple uploads

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#333]
Regarding Chrome console log : -

a)  localhost:9000/add/recipe
b) Also the two storybook sections for the FileUploadWidget

> Warning: Failed prop type: Invalid prop `value.data` of value `[object Object]` supplied to `FileUploadWidget`, expected one of [null,null].

This is a sister issue to  

#331 which moves a fullWidth property up into a FormControl

#325 Which will fix a  recurring key issue.

**Comment by martinfrances107** [comment]
I have changed the title because this is now effectively a follow up to #337 .

It fixes issues that remain for the case of multiple files uploads.

**Comment by dawehner** [comment]
The current list of proptypes seem to not longer come from the ```FileUploadWidget```. Given that I'll close this :)
