### ISSUE TITLE
Storybook: Apply interactivity consistently

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#334]
While thinking about ways to proceed with (#330) -- adding storybook assets - this side issue because obvious.

We have existing interactivity...

If you look at the storybook entry for the Message element... on the knobs panel, it is possible for the user to interact with and therefore alter the text.

This issue is a single minded thought... 

> ### **We should apply 'boolean', 'object', 'number' and 'text' knobs throughout the design.**

Other minor changes 

1) DatetimeTimestamp -- now has a sample date set.

2) TextTextarea - now used to a standard typographers example text as the default value. 

PS I have also fixed up a trivial bug... recently a PR was merged in the area of marking fields as required, this lead to a console error when viewing the storybook definition of DateTimestamp as the required field is required and the .stories file needed to be updated.

I am about to upload a PR.

**Comment by dawehner** [comment]
w00t
