### ISSUE TITLE
Reducer type error. 

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#356]
Error when visiting

 http://localhost:3000/node/add

as seen in the Chrome's console logs

index.js:2178 

uncaught at loadContentTypes TypeError: action.payload.contentTypes.data.reduce is not a function
    at ./src/reducers/application.js.__webpack_exports__.a

**Comment by francescopersico** [comment]
I can't reproduce this bug. No console error on http://localhost:3000/node/add.

**Comment by francescopersico** [comment]
Got the cause of the problem. Going to fix it.
