### ISSUE TITLE
Storybook: OptionsSelect 'allowed_values' needs updating

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#364]
Options select was recently updated #274 

I am not sure if it is connected but the storybook entry needs to be updated.

![optionsselectstorybook](https://user-images.githubusercontent.com/1259969/44362083-dab3ff80-a4b7-11e8-9aee-5b520f769d5f.png)

**Comment by dawehner** [comment]
Thank you so much for carrying about the storybook
