### ISSUE TITLE
Type errors on /node/add/page & /node/add/recipe

### ISSUE THREAD

**Issue by vishalchandna1** [jsdrupal/drupal-admin-ui#374]
Facing type errors 

`/recipe`

<img width="599" alt="recipe" src="https://user-images.githubusercontent.com/13252288/44400458-d8f64480-a568-11e8-8190-3a92a36801bc.png">

`/page`

<img width="531" alt="screen shot 2018-08-21 at 6 15 00 pm" src="https://user-images.githubusercontent.com/13252288/44402244-cbdc5400-a56e-11e8-9a05-8b813af7cad3.png">

<img width="599" alt="page" src="https://user-images.githubusercontent.com/13252288/44400459-d8f64480-a568-11e8-92e8-f4d90a16f436.png">

**Comment by rahulsavaria** [comment]
Hi @lauriii,

I would like to work on this issue, can you please assign it to me.

Thanks

**Comment by dawehner** [comment]
@rahulsavaria Feel free to work on it already. I invited you to the github org, which is needed first before we can assign you.

**Comment by vishalchandna1** [comment]
@dawehner  It actually requires the change from the Drupal side. As you can see the `promote` attribute in the response is an integer but it should be a boolean as defined in our props. 

@rahulsavaria  is already working on it, so we can expect its PR soon :)
