### ISSUE TITLE
Attached file is not retrieved when file field only allows uploading a single field

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#383]
It seems like attached files are not retrieved when file field only allows uploading a single field. This can be tested for example with article content type using umami.

Steps:
1. Create new article with image and save
2. Go to edit the created node - the image field should be empty
3. Visit the node edit on the legacy admin UI and see that the image is attached

This doesn't affect the Drupal Europe demo because we change the field from allowing a single value to allow multiple values.

**Comment by dawehner** [comment]
I do have the article form just allowing one item and it works as expected. I think we can close this issue down :)
