### ISSUE TITLE
Fetch the human readable label for bundles instead of using the machine name

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#385]
Currently, at least in a few places, we use the machine name of a bundle in the UI. Instead of relying on showing the machine name of the bundle, we should fetch and show the human readable label.

**Comment by lauriii** [comment]
There's now an example of how this could be done. See usages of `mapContentTypeToName` for more info.

**Comment by gbamparop** [comment]
@lauriii could you please let us know where did you find the issue? A screenshot would definitely help. Thanks

**Comment by lauriii** [comment]
I think this is outdated indeed. I think we are using `mapContentTypeToName` at least fairly consistently now. If there are specific instances where this is not the case, we should open separate issues for that.
