### ISSUE TITLE
HTML in formatted text saved in the app doesn't render correctly

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#386]
If you save formatted text in the admin UI app, it doesn't get rendered correctly in Drupal.

For example, following content:
![screen shot 2018-08-22 at 00 48 44](https://user-images.githubusercontent.com/1845495/44419368-2690a280-a5a5-11e8-992d-4a0103f10857.png)

Renders like this in Drupal:
![screen shot 2018-08-22 at 00 46 35](https://user-images.githubusercontent.com/1845495/44419359-1c6ea400-a5a5-11e8-9a58-fb9447cfbc42.png)

**Comment by dawehner** [comment]
Yeah, this got resolved too :)
