### ISSUE TITLE
Ensure that snackbars shown one by one

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#389]
[According to Material UI style guide](https://material-ui.com/demos/snackbars/), snackbars can be only shown one at a time. Currently, if multiple messages are dispatched simultaneously, they are all shown at once. Change the logic that only one snackbar is shown at once.

![screen shot 2018-08-22 at 16 03 40](https://user-images.githubusercontent.com/1845495/44454259-3c45ac80-a625-11e8-9917-a6560b31d5ad.png)

**Comment by abhaykumar1415** [comment]
i want to work on this issue.. thanks
