### ISSUE TITLE
Umami patch no longer applies

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#408]
There is a patch which ensures that umami doesn't use workflow, as we don't support it yet

Sadly this patch currently doesn't apply:
```

    patches/remove-umami-workflows-dependency.patch (Remove Umami dependency to Workflows because the admin UI doesn't currently support it)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/remove-umami-workflows-dependency.patch

  - Installing drupal/schemata (1.0.0-alpha3): Loading from cache```

**Comment by martinfrances107** [comment]
While I am working on this I am providing a little context 

When I reroll this patch on D8.7.x 

> CONFLICT (modify/delete): core/profiles/demo_umami/config/install/user.role.editor.yml deleted in ap and modified in HEAD. Version HEAD of core/profiles/demo_umami/config/install/user.role.editor.yml left in tree.

Anyway it is not immediately clear to me which core patch broke our stuff,  I have yet to do the appropriate binary search and git blame thing.. but I will sort this out this weekend...

**Comment by martinfrances107** [comment]
I have moved the patch to the upstream repository

**Comment by martinfrances107** [comment]
I think I have now fixed the problem.

**Comment by dawehner** [comment]
Yeah! Thanks a ton!
