### ISSUE TITLE
Confirmation Dialog Inappropriate template nesting

### ISSUE THREAD

**Issue by vishalchandna1** [jsdrupal/drupal-admin-ui#416]
A warning message is received when confirmation dialog template is rendered which is `<ul>` cannot be descendent of `<p>`

<img width="733" alt="screen shot 2018-08-27 at 1 08 23 pm" src="https://user-images.githubusercontent.com/13252288/44650014-29572180-aa03-11e8-9048-fed1236ade12.png">

**Comment by martinfrances107** [comment]
@vishalchandna1 , hi I think this issue can be closed now...
