### ISSUE TITLE
Drupal Europe discussion plan

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#424]
Here are a couple of questions we should maybe try to address during Drupal Europe

* How to collect feedback from people related to the demo?
* How will we integrate the app into Drupal? How to get feedback and signoff from the core maintainers?
* How can we improve the test coverage?
* Roadmap and the goals for the next 6 months / 12 months
  * Some ideas:
    * Media integration
    * Creating / managing taxonomy terms
    * Better comment management UI
    * Localization of the UI
    * Translation support
    * Workflow support
    * Revisions support
    * Stabilizing the content authoring part
* **Find and tag issues as "Good first issue" for the sprint day to get more people involved?**
* Enable login in via the admin UI

**Comment by mattgrill** [comment]
- Field level constraints.

**Comment by dawehner** [comment]
It is done and was great
