### ISSUE TITLE
How much data should we provide to be restored

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#432]
https://github.com/jsdrupal/drupal-admin-ui/pull/429 and https://github.com/jsdrupal/drupal-admin-ui/pull/357 introduced a feature which allows to automatically "save" content on the client and restore it later.

The way it works right now would blow up local storage over time, which isn't ideal, as for example it would no longer store it.

**Comment by mattgrill** [comment]
@dawehner Do we make sure to remove the data from local storage if they choose to restore it?

**Comment by dawehner** [comment]
Well, there is that but also storing content by entity ID increases the
storage too much potentially

**Comment by dawehner** [comment]
I think we are fine with the current state of things :)
