### ISSUE TITLE
Reduce complexity:  One Dialog element per table.

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#433]
Regarding the OpsModalButton, I think I casually introduced a pattern which is responsible for slow page loading which I now want to refactor.

The current problem is that we have one hidden dialog associated with every table row, or for every button

Each DIALOG is a structure with 12 base html element ( BUTTON, DIV, P,, SPAN etc )  

This has scaling problems, currently the list content page has 12 rows so that is 144 elements.

I can think of projects where I want 25 rows per table. ( 300 elements ) 

I have created a PR with a new OpsTableElement which contains centralized DIALOG element.
all table sub elements are wrapped in a react "context"  so all child  OpsModalButton's can call a openDIalog method held within that  context which populates the dialog and then unhides it.

I have the skeleton of the code worked out ... it has a few bugs ... 
on the storybook page only click the OpsModalButton the Dialog opens, it can be closed... but not opened a second time., but this is work in progress so I am just showing the idea...if anyone has objections then it can be restructured or shot down early.

**Comment by dawehner** [comment]
I would measure first here :) measure what it takes to render right now,
make improvements and look at it again. I think conceptually what you write
make sense and rendering less Dialogs would help a lot.

**Comment by martinfrances107** [comment]
With the next iteration I will provide timing evidence .. good or bad.

But by way of providing supporting evidence -- I want to advance the line that we should do this even if the timing is not significantly improved - because of scaling concerns.

Chrome's lighthouse auditing tools: in the performance section. There are comments about an overly complicated DOM structure 

The total number of DOM elements is about 80% of the failure threshold ( which is a pass ) 

BUT we are getting warnings saying 

The number of descendant children is too large 

html  ...  table->tbody->trow->tcell -> before our dialog and its 12 elements.

I think other developers in contrib are going to want to create far more complex tables that the one we are basing our design around. Certainly many are going to want to set the pagination upto to a table with 25 or 50 rows ... and which point as I tried to point out in the main issue .. the table structure does not scale. The  20%  headroom before the DOM element count fails - will be easily consumed.

Regarding performance I want to highlight a second issue. Well for me the original issue.

The animation performance of the side drawer opening is a horrendous 2-4 fps.  ( on a low end laptop ) so mobile should be worse.

I have pofiled the animation  .. and the cause is a per frame resizing of the table as the drawer opens.
The standard way forward on that issue is to push the drawer or the table into its own render layer - and then then the GPU will transform the moving layer as a sprite.

That analysis was the starting point for this issue. The seed behind this issue what I regard as an orthogonal side issues.

a) Reducing DOM complexity 
b) Finding a lazy evaluation pattern 

Anyway just saying I appreciate the complexity of performance issues .. and I am thinking of spawning a new issue for the render layer .. but hey I have too many issue open at the moment.

**Comment by martinfrances107** [comment]
just binding this issue to the PR #434

**Comment by martinfrances107** [comment]
The arguments I have been making about Lighthouses code complexity need correction

When I compare the audit reports for the before and after, the complex and the simplified.

I see that the count is the same 745 nodes.

The javascript is downloaded, parsed executed and before the creation of the DOM tree. But only element visible on the screen are added to the tree.

So the 745 comes from what is on the screen ( ie no dialog in both cases ) 

Lighthouse does not count the reduced complexity as a  benefit and the metric does not change!

If the real compute cost comes after the DOM tree is populated then ... I am driving full speed down a side track.

Just though I should point that out as soon as I saw it.

**Comment by martinfrances107** [comment]
I don't think this refinement will drive the complexity score in the direction that matters.

@dawehner thank you for following along and asking questions - 

but this can be closed.
