### ISSUE TITLE
TypeError on widgets.

### ISSUE THREAD

**Issue by anjiv** [jsdrupal/drupal-admin-ui#437]
<img width="992" alt="screen shot 2018-08-30 at 12 54 14 pm" src="https://user-images.githubusercontent.com/25002064/44836174-d1632980-ac53-11e8-9773-9fc16c11089f.png">

**Comment by anjiv** [comment]
@dawehner I have updated the PR and added the documentation for object shape. Thanks for the heads up regarding the documentation :)

**Comment by dawehner** [comment]
Thank you @anjiv
