### ISSUE TITLE
Error messages not rendering properly for File upload widget

### ISSUE THREAD

**Issue by anandtoshniwal** [jsdrupal/drupal-admin-ui#442]
Steps to reproduce

Add any format which is not acceptable, you will see the errors as below
![screen shot 2018-08-30 at 5 12 49 pm](https://user-images.githubusercontent.com/15143023/44849514-fbc6de00-ac77-11e8-9492-12856319b2d6.png)

**Comment by dawehner** [comment]
Oh nice finding

**Comment by anandtoshniwal** [comment]
Hi @dawehner ,
Already started working on this, can you please assign it to me ?
