### ISSUE TITLE
Place `justafish/drupal-admin-ui` in a more standard location

### ISSUE THREAD

**Issue by balsama** [jsdrupal/drupal-admin-ui#460]
Right now, `justafish/drupal-admin-ui` is placed in `docroot/vfancy` and needs some special instructions in the root composer.json file to make it end up there. Would it be possible to refactor the app so that it looks for that code in `docroot/libraries`? That way we could potentially create a package which would allow one to bring in and use the JS Admin theme without the custom `drupa-amin-ui-demo` scaffold project.

Proposed resolution:
1. Add [`type:drupal-library` to `justafish/drupal-admin-ui` composer.json](https://github.com/jsdrupal/drupal-admin-ui-dist/blob/master/composer.json)
2. Remove the [special instructions for it in the scaffold project's composer.json](https://github.com/jsdrupal/drupal-admin-ui-demo/blob/master/composer.json#L73)
3. Do whatever is necessary to the app itself so it looks for that code in /docroot/libraries instead of /docroot/vfancy.

3️⃣is obviously the hard one and I don't know what that would entail. So I wanted to check if this was even possible.

**Comment by dawehner** [comment]
Hi Adam.

The way how we plan this application to work is not to embed it into an existing Drupal site. It is  designed to be fully decoupled.

> is obviously the hard one and I don't know what that would entail. So I wanted to check if this was even possible.

Yeah indeed. Our solution with the vfancy folder, certainly not the best name, allows us to solve this hard problem.

**Comment by justafish** [comment]
To elaborate a little - the vfancy folder exists underneath docroot because it's all served directly from the webserver instead of via Drupal. We rewrite the address in the browser with the History API to make it look like it's under `/admin`.
