### ISSUE TITLE
Console erorrs on taxonomy page

### ISSUE THREAD

**Issue by anandtoshniwal** [jsdrupal/drupal-admin-ui#462]
![screen shot 2018-09-13 at 5 17 14 am](https://user-images.githubusercontent.com/15143023/45459083-54848500-b714-11e8-948d-bc69dac6dbe6.png)

**Comment by anandtoshniwal** [comment]
@dawehner started working on this, will Raise PR soon

**Comment by dawehner** [comment]
Thank you for fixing this problem @anandtoshniwal
