### ISSUE TITLE
Add Input label for actions and console errors 

### ISSUE THREAD

**Issue by anandtoshniwal** [jsdrupal/drupal-admin-ui#474]
Add Input label for actions on taxonomy and taxonomy term overview page
console errors on taxonomy term overview page
Please check the screenshots below
![screen shot 2018-09-14 at 12 34 12 pm](https://user-images.githubusercontent.com/15143023/45538442-b7fdd800-b824-11e8-9407-5e07ed277073.png)
![screen shot 2018-09-14 at 12 35 09 pm](https://user-images.githubusercontent.com/15143023/45538455-c4823080-b824-11e8-9822-f9f166a93ffa.png)

**Comment by dawehner** [comment]
The PR for this got merged. Thanks a lot for your contributions!
