### ISSUE TITLE
404 Error in API - /entity-schema/node/:id

### ISSUE THREAD

**Issue by vishalchandna1** [jsdrupal/drupal-admin-ui#479]
1. Go to Edit button on content page
2. A 404 error occurs.

<img width="1215" alt="screen shot 2018-09-14 at 5 12 14 pm" src="https://user-images.githubusercontent.com/13252288/45548349-aaa31680-b841-11e8-8c6c-4d1a9b21402e.png">

**Comment by dawehner** [comment]
You need to update the module, our ```admin_ui_support``` module was adapted in the meantime.
