### ISSUE TITLE
NIghtwatch tests failing due to content_moderation

### ISSUE THREAD

**Issue by alexburrows** [jsdrupal/drupal-admin-ui#495]
When running tests via `yarn test` the first set of tests pass, but upon creating content tests fail.
See here - https://circleci.com/gh/jsdrupal/drupal-admin-ui/6617?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Patch **remove-umami-workflows-dependency.patch** needs to be rerolled to resolve this and ensure content_moderation is not enabled in any way.

**Comment by mattgrill** [comment]
The patch is supplied from the demo repo. I've rerolled it here, https://github.com/jsdrupal/drupal-admin-ui-demo/pull/38

**Comment by mattgrill** [comment]
Alright. This should be fixed. Thanks!
