### ISSUE TITLE
Update README with installation details

### ISSUE THREAD

**Issue by vijaycs85** [jsdrupal/drupal-admin-ui#498]
###  Problem
Not sure if it's just me, but when I follow the [development instructions](https://github.com/jsdrupal/drupal-admin-ui#developing), `composer devify` did not create `drupal-admin-ui/build` directory. However, the command did not fail either.  Created broken symlink `docroot/vfancy`. 

```
➜  drupal-admin-ui-demo composer devify
> git clone https://github.com/jsdrupal/drupal-admin-ui
Cloning into 'drupal-admin-ui'...
> cp drupal-admin-ui/.env drupal-admin-ui/.env.local
> cd drupal-admin-ui && yarn install
yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 23.92s.
> rm -rf docroot/vfancy
> ln -s ../drupal-admin-ui/build docroot/vfancy
> rm -rf docroot/modules/contrib/drupal-admin-ui-support
> ln -s ../../../drupal-admin-ui/admin_ui_support docroot/modules/contrib/drupal-admin-ui-support
```

### Solution:
Running `yarn build` explicitly fixed the symlink and works with switching as well.

**Comment by mattgrill** [comment]
@vijaycs85 Could you provide some more information about your environment and the steps you took prior to running `devify`?

**Comment by martinfrances107** [comment]
I think the location of packages/admin-ui/.env recently moved and things are out of date in the devify script

 From what I can tell after the 

git clone ...

regarding the cp instruction the location of the .env file is 

drupal-admin-ui/packages/admin-ui/.env 

here is the current devify script. -- showing the discontinuity

```
            "git clone https://github.com/jsdrupal/drupal-admin-ui",
            "cp drupal-admin-ui/.env drupal-admin-ui/.env.local",
            "cd drupal-admin-ui && yarn install",
            "rm -rf docroot/vfancy",
            "ln -s ../drupal-admin-ui/build docroot/vfancy",
            "rm -rf docroot/modules/contrib/drupal-admin-ui-support",
            "ln -s ../../../drupal-admin-ui/admin_ui_support docroot/modules/contrib/drupal-admin-ui-support"
```

**Comment by martinfrances107** [comment]
also looking at the devify script listed above 

"ln -s ../drupal-admin-ui/build docroot/vfancy",

the paths here need adjustment

"ln -s . ../drupal-admin-ui/packages/admin-ui/build/ docroot/vfancy",

**Comment by martinfrances107** [comment]
just going back from a clean install and documenting all the problems

We need to revisit the scripts and adjust for the recent file moving

When I run composer setup and get to this line

cd docroot && ../vendor/bin/drush en -y jsonapi admin_ui_support

```
In PmCommands.php line 259:
                                                                               
  Unable to install modules: module 'admin_ui_support' is missing its depende  
  ncy module openapi. 
```

**Comment by martinfrances107** [comment]
The instructions have been comprehensively reworked  recently .. and I think all issues have been resolved.
