### ISSUE TITLE
NumberTextField: Mishandled unsigned property

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#506]
The storybook entry for NumberTextField is currently broken.

Here is the error message 

> Cannot read property 'toString' of undefined
> TypeError: Cannot read property 'toString' of undefined
> 

The bug is :- 

A missing / unrecognised dependancy. In short we need a valid  propType and sensible default pair for 

NumberTextField.inputProps.unsinged 

I am creating a PR now.

**Comment by martinfrances107** [comment]
Hmm I cannot justify the use of **unsigned** here

It looks like unsigned is not a valid property of either 

A) the material-ui/core/input object

 or

B)  the underlying html input element.

I maybe wrong about this ... but with the PR storybook now works.

**Comment by dawehner** [comment]
Thank you @martinfrances107 !
