### ISSUE TITLE
Epic: Extension points

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#510]
Explore how the Drupal module system can inject changes into the React Admin UI, and after that, explore some specific APIs, such as Field Widgets, and provide prototypes for those.

For more details, see:
https://docs.google.com/document/d/1U1O4VK0CKbz--aPD5o4WvbQJ6Ss0_T8EX3xntbGdwVo/edit#

**Comment by mattgrill** [comment]
Lets close this and continue the discussion in the existing issue.
