### ISSUE TITLE
Menu navigation is possibly broken and URL rewriting has unexpected results. 

### ISSUE THREAD

**Issue by mattgrill** [jsdrupal/drupal-admin-ui#53]
![navigation-issues](https://user-images.githubusercontent.com/1090713/37921561-036b7ef0-30df-11e8-876a-7481fa912138.gif)

**Comment by tedbow** [comment]
Does this issue fix this https://github.com/jsdrupal/drupal-admin-ui/pull/55?

**Comment by dawehner** [comment]
Yes it is.

**Comment by mattgrill** [comment]
Fixed!
