### ISSUE TITLE
Bring in the dblog page from https://github.com/jsdrupal/drupal-react-db-log

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#54]

**Comment by martinfrances107** [comment]
How would you like to bring the project in ..... 

as a submodule, or abandon that project and subsume the code into this one?

Just asking cos 

http://127.0.0.1:3000/admin/reports/dblog 

is failing at the moment Reporting  404 on a failed routing to the watchdog_entity.

So this is a higher priority than a realised ... I am happy to work on it.

**Comment by mattgrill** [comment]
@martinfrances107 We've already mostly brought over that code. Since it looks like you've discovered an issue with the dblog page, _an issue with a json api resource_, lets maybe close this issue and open another.

**Comment by martinfrances107** [comment]
@mattgrill thanks for the quick reply....

Ok I now have a quick fix for the 404'ing in issue #197

**Comment by martinfrances107** [comment]
I did not want to speak until I had a chance to look over the other repo....

looking at code differences ... the other codebase is much less developed and I think it does not have much to offer

.... in short I think this issue can be closed.

**Comment by dawehner** [comment]
This was done at least for now :|
