### ISSUE TITLE
JSX elements are not being linted fully

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#555]
This maybe a deliberate design choice that I am ignorant of 

BUT 

we are getting compile errors in relation to storybook when we have JSX elements inside js files
[ that is being fixed here #554 as part of #546 ]

This issue is separate I just want clearance to lock this down so that all files using JSX elements have the extension jsx or tsx.

**Comment by dawehner** [comment]
It looks like there is a disagreement between airbnb and people working on react itself, see https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

Personally I think I agree with @gaeron's perspective.

**Comment by martinfrances107** [comment]
I am happy to follow the no jsx files convention

BUT I am seeing some horrible interaction with our current linting configuration files

case in point if you rename AddContent.test.js to  AddContent.test.jsx 

then you get **new** linting errors 

> Warning: validateDOMNesting(...): <div> cannot appear as a descendant of \<p\>.

I am going to look into this more so that we get the same error warning from js files with JSX elements.

**Comment by dawehner** [comment]
> I am going to look into this more so that we get the same error warning from js files with JSX elements.

**Comment by dawehner** [comment]
>  I am going to look into this more so that we get the same error warning from js files with JSX elements.

Nice, thank you!

**Comment by martinfrances107** [comment]
Great - the loose ends are complete and merged.. 

thank you.
