### ISSUE TITLE
Convert NoMatch.tsx to NoMatch.ts

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#556]
This is just a tiny change

We have recently converted files with a JSX extension to have  a JS extension.

In another issue dawehner has provided a link to the reasons why...

> It looks like there is a disagreement between airbnb and people working on react itself, see facebook/create-react-app#87 (comment)

The NO JSX policy is fine with me ... This is a small followup we should also have a NO TSX policy
NoMatch tsx the only file to be changed.

**Comment by dawehner** [comment]
👍

**Comment by martinfrances107** [comment]
Here is the associate PR #557

 -- for some reason the auto linking between PR and main issue failed.. hmmm

**Comment by martinfrances107** [comment]
The merge is in .. thank you.
