### ISSUE TITLE
Prop type validation error on loading the menu tree

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#56]
Menu tree resource property `subtree` is an object when there are values, but an array when the list is empty. Currently, we are only expecting for an object type of values on this property.

**Comment by dawehner** [comment]
Wow, that's pretty "nice" :) Given that these keys are mostly meaningless anyway I think adapting the normalizer on the PHP side isn't the worst idea.

**Comment by lauriii** [comment]
Fixed on #57
