### ISSUE TITLE
Figure out  how to call APIs  from within extension points

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#571]
I wanted to work on https://github.com/jsdrupal/drupal-admin-ui/issues/295 and  stumbled an  issue:  How are we gonna make it possible to call the Drupal endpoint. My naive approach laid out in [here](https://github.com/dawehner/drupal-admin-ui/blob/77e692367072f5068146bb310fc2ac7b5573f038/examples/admin_ui_content_moderation/js/src/moderation_state_default.widget.js) results into:

```
 ./node_modules/.bin/extension-points-bundler
Hash: d9295f6d4b06b44dedac
Version: webpack 4.26.0
Time: 774ms
Built at: 12/03/2018 9:35:03 PM
                             Asset      Size  Chunks  Chunk Names
moderation_state_default.widget.js  8.18 KiB       0  moderation_state_default.widget
Entrypoint moderation_state_default.widget = moderation_state_default.widget.js
[0] external "react" 42 bytes {0} [built]
[1] ./js/src/moderation_state_default.widget.js 3.38 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./js/src/moderation_state_default.widget.js
Module not found: Error: Can't resolve 'drupal-admin-ui/src/api' in '/Users/dawehner/www/drupal-admin-ui-demo/drupal-admin-ui/examples/admin_ui_content_moderation/js/src'
 @ ./js/src/moderation_state_default.widget.js 22:0-42 53:6-9
```

* [ ]  Let module authors  figure it  out by themselves, might  be impossible
* [ ] Publish the entire admin-ui on NPM, feels weird
* [ ] Build a utilities library like  `admin-ui-utilities` and expose  that on NPM. 
*  [ ] Pass along the API function as context

**Comment by mattgrill** [comment]
I think that publishing something like `admin-ui-utils` make sense.

**Comment by dawehner** [comment]
> I think that publishing something like admin-ui-utils make sense.
Yeah that was kind of  my feeling as well. Maybe we could like to provide react hooks at some point for example.

**Comment by mattgrill** [comment]
@dawehner We should probably agree on what should go in this util library?

**Comment by dawehner** [comment]
@mattgrill It feels like the only really useful thing right now is  this API helper.

**Comment by mattgrill** [comment]
I think this is solved now?

**Comment by dawehner** [comment]
totally
