### ISSUE TITLE
Docker volume permissions

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#599]
Currently if you want to edit any code in Drupal core, you either have to explicitly change permissions on the file or edit it from the container. This is the case for Linux, not sure if the same thing is happening on a Mac.

If we could map the Docker user to the current user when the containers are being built that would be great, but I don't think all shells contain the `$UID` and `$GID` environment variables.

**Comment by justafish** [comment]
Another option could be running Apache as root :rotating_light: :policewoman:

**Comment by dawehner** [comment]
As you wrote in some other issue, these containers are not intended for production usage. Given that security of running it as a root wouldn't be that much of an issue :p  

For the GID/UID issue I see two possible solutions:

1. Wrap docker-compose up in a `#!/usr/bin/env bash` script. This way $UID/$GID is available
1. Somehow set/use UID/GID leveraging the id command line tool, which seems to be part of coreutils, which might be available all the time?

**Comment by martinfrances107** [comment]
After playing around with this branch some more.

when I visit http://127.0.0.1

I can see a little screw up concerning png and jpg files

in chrome's devtools -- console window I see 9 errors  with http code 500 "Internal server error"

below I am quoting just 2 of the errored links.

within .docker/drupal/nginx.default.conf I can see setup for 

image files 

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri @rewrite;
        expires max;
        log_not_found off;
    }

but I think there is a conflict with 

    location ~ ^/sites/.*/files/styles/ {
        try_files $uri @rewrite;
    }

Anyway I will try and fix this tomorrow.


http://127.0.0.1/sites/default/files/styles/medium_8_7/public/umami-bundle.png?itok=92iAaAEI

http://127.0.0.1/sites/default/files/styles/scale_crop_7_3_large/public/veggie-pasta-bake-hero-umami.jpg?itok=Z-0248WD

**Comment by martinfrances107** [comment]
Minor housekeeping, and good news - I think this issue can be closed now.
