### ISSUE TITLE
Menu items are loaded from API after every location change

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#62]
The menu items are being loaded from the Drupal API after every location change.
![screen shot 2018-03-29 at 18 11 03](https://user-images.githubusercontent.com/1845495/38086604-3725ee2c-337f-11e8-9822-3fe198198223.png)

**Comment by justafish** [comment]
I was going to suggest wrapping `this.props.requestMenu();` in a check to see if `this.props.menuLinks` has data before calling it, however I'm curious why it's doing that as it shouldn't be remounting the Default wrapper on each request

**Comment by justafish** [comment]
ah, this was introduced by https://github.com/jsdrupal/drupal-admin-ui/pull/55 - we probably should revert that and figure out another fix for that bug
