### ISSUE TITLE
Storybook: Fix issue with FileUpload

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#632]
There is a issue to create a container for storybook

https://github.com/jsdrupal/drupal-admin-ui/issues/630
https://github.com/jsdrupal/drupal-admin-ui/pull/631

Now that we have a candidate storybook sever, it is clear that we have not been keeping the storybook definitions current. 

I want to fix all the errors with storybook.js files here.

**Comment by martinfrances107** [comment]
ok looking arround the net for similar bugs 

it looks like it is a common error when people try and configure CRA with type script / commonjs

here is on suggestion from 

https://github.com/webpack/webpack/issues/3974

In your tsconfig.json:
Make sure you have this:

    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node"
I have accidentally put module: "commonjs" and that was causing this error.

In your .babelrc:
Make sure you have set modules to false and loose to true:

"presets": 
[
   [      
      "env",
      {
        "modules": false,
        "loose":  true,
        // ...

**Comment by iberdinsky-skilld** [comment]
on my side setting https://babeljs.io/docs/en/babel-preset-env#modules fixed the problem
[![Image from Gyazo](https://i.gyazo.com/a6b5e2dccfd87387ff7119ed14969c5e.png)](https://gyazo.com/a6b5e2dccfd87387ff7119ed14969c5e)

**Comment by iberdinsky-skilld** [comment]
and this is not only issue with FileUpload.stories. when i deleted that file error was with next component

**Comment by iberdinsky-skilld** [comment]
environment still not really clear for me. so i'm not sure should i create PR here.

**Comment by martinfrances107** [comment]
@iberdinsky-skilld  thank you very much for looking at this... and for providing the solution

I will find time to have a review of your solution this weekend.

What gives me pause for thought is making being sure this compatible with the tsconfig.json files settings given to us by React CRA. and making sure that changing this setting from "auto" (the default) to false does not have any unforeseen consequences down the line. 

For example here is a user - asking for help with tree shaking -- with his reasoning as to when module false causes problems. 

https://stackoverflow.com/questions/47663486/webpack-3-babel-and-tree-shaking-not-working

I am not saying we have the problem .. I just want to do a little investigation.

**Comment by iberdinsky-skilld** [comment]
sure, why not.

**Comment by iberdinsky-skilld** [comment]
seems storybook issue 
https://github.com/storybooks/storybook/issues/4672
