### ISSUE TITLE
Add storybook? styleguide and plan component development

### ISSUE THREAD

**Issue by pixelmord** [jsdrupal/drupal-admin-ui#65]
I saw that issue #7 mentions the "bonus" of a storybook story for the permissions page and #17 deals with components that are Drupal Admin specific.

I think it would be a good idea to 
1. have a storybook style guide for this project to enable style development asynchronously to feature implementation
2. to create an architecture where we do not copy paste components between react-drupal-components and this project, but for example, require drupal-react-components as a dependency lib.

Then we can decide if a component like the `Message` component should also go to the more general Drupal components in the drupal-react-components project, where people with a Drupal background could use them for all kinds of React projects.

I think that would make a sustainable solution that would only need a bit of refactoring in the already existing components to make them compatible with emotion or other concepts of providing styles through passing in className as a prop.

**Comment by dawehner** [comment]
I agree we should copy over the work we did on the components branch over here: https://github.com/jsdrupal/drupal-react-components

**Comment by pixelmord** [comment]
@dawehner I do not understand completely what you mean?
I was proposing to let the `jsdrupal/drupal-react-components` project continue and require it as a dependency by `jsdrupal/drupal-admin-ui` so the latter can be concerned with functional components and the presentational stuff can be developed in the former project.

In the drupal-react-components we might want to refactor a bit to make it compatible with both classNames provided as plain strings and ones generated by emotion...

However, I can also understand when we do not want to go multi-repo from the get-go...

**Comment by justafish** [comment]
We discussed this a few meetings ago, but we'll probably go the route of [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/), but for now just trying to keep things relatively simple whilst we get our feet off the ground

**Comment by dawehner** [comment]
We've  added storybook; yeah!
