### ISSUE TITLE
 Input checkbox

### ISSUE THREAD

**Issue by antonellasevero** [jsdrupal/drupal-admin-ui#659]
https://www.figma.com/file/OqWgzAluHtsOd5uwm1lubFeH/Drupal-Design-system?node-id=2061%3A2386

MDN Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

![input-checkbox-anatomy](https://user-images.githubusercontent.com/24964925/54877135-c69ffa00-4e1a-11e9-9b38-9283b24b582d.jpg)

![input-checkbox-states](https://user-images.githubusercontent.com/24964925/54877138-c7389080-4e1a-11e9-8730-33fd01038fd0.jpg)

![input-checkbox-examples](https://user-images.githubusercontent.com/24964925/54877136-c69ffa00-4e1a-11e9-8c49-ea7dc703062c.jpg)

![input-checkbox-quick-specs](https://user-images.githubusercontent.com/24964925/54877137-c7389080-4e1a-11e9-8636-62b21952d990.jpg)

## Technical details

* [x] Create  a Label component inside `packages/components/FormElements/InputCheckbox/InputCheckbox.js`
* [x] Implement the  component following the design from above
* [x] Add a storybook entry: `packages/components/FormElements/InputCheckbox/InputCheckbox.stories.js`
* [x] Ensure to export to `packages/components/src/index.js:6`
* [x] Please ask when you questions :)
* [x] Enjoy

**Comment by martinfrances107** [comment]
I think this is complete.
