### ISSUE TITLE
Stub out the permissions page

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#7]
## API Endpoints Needed
- [list of permissions](https://www.drupal.org/project/drupal/issues/2947605)
- Roles and Permissions (config entities) are available from JSON API

We're already going to be on the same domain as Drupal, meaning we can use Cookie authentication, so we can use the browser's fetch API directly for this.

## Components Needed
- [Table (with sticky header)](https://github.com/jsdrupal/drupal-react-components/tree/master/src/components/table)
- [Checkbox](https://github.com/jsdrupal/drupal-react-components/tree/master/src/components/checkbox)

## Submit Function
I'm not sure if we can write the config entities through JSON API yet, so for now let's pretend it's making a successful request with an artificial delay

## Permissions Page
Component skeleton is [here](https://github.com/jsdrupal/drupal-admin-ui/blob/master/src/components/05_pages/Permissions/Permissions.jsx), with ability to add CSS 
See also https://github.com/jsdrupal/drupal-admin-ui/tree/master/src/styles for global styles

## Jest Test
Can be added as an additional file in https://github.com/jsdrupal/drupal-admin-ui/tree/master/src/components/05_pages/Permissions

## Bonus Round
It would be great to add Storybook to this project and add a .story file into https://github.com/jsdrupal/drupal-admin-ui/blob/master/src/components/05_pages/Permissions

**Comment by justafish** [comment]
Should we start importing the components into this repo so it's all in one place?

**Comment by dawehner** [comment]
@all Do you consider this stub out to be successful?

**Comment by tedbow** [comment]
@dawehner it is probably good for a stub. 

It would be good if there was message that the permissions were saved but maybe we could do that in follow up?

**Comment by dawehner** [comment]
Yeah let's open follow ups.

**Comment by dawehner** [comment]
I opened up another follow for some other details.

**Comment by dawehner** [comment]
I'd say we are good on that one.
