### ISSUE TITLE
react-scripts update to 3.0.1

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#733]
As part of ensuring we use the latest create react app.

We need to bump the major version of react-scripts 

- "react-scripts": "2.1.1",
+"react-scripts": "3.0.1",

A few other changes we forced upon me in order to run  http://localhost:3000/

the eslint version had to be bumped.

I am about to generate to pull request.

**Comment by martinfrances107** [comment]
I think the  associated PR is ready for review ...

Here is a summary of the changes 

1) My motivation was to upgrade to the latest create-react-app. There are minor incremental improvements to typescript support.

2) Practically the means a bump in the react-scripts version number.
2a The new react-scripts reports errors unless the eslint version number is bumped. 
2b) The updated linter reports deprecated warning associate with the history package [ which was updated and our code updated] 
2c) The updated linter demands some proptypes be locked/down for tests to pass.

**Comment by dawehner** [comment]
@martinfrances107 thank you for your great PR! I've merged it :0
