### ISSUE TITLE
Adapt the README to use --depth and use the 8.6.x branch to ease the install process

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#82]

**Comment by lhuria94** [comment]
Hi @dawehner, I can pick this up if you can explain a bit more about what is the exact expectation here?

**Comment by dawehner** [comment]
@lhuria94 Hi! Sorry for my late reply. I think this task is no longer useful, as we do have a devify command now :) 

Please come to our meeting in 3 minutes though, if you have time.
