### ISSUE TITLE
Implement simple content listing page

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#85]

**Comment by tedbow** [comment]
To support this I am looking what it would take for create `/jsonapi/node` resource that would allow collections of nodes(another entity types) across bundles.

It doesn't look like the *jsonapi* module itself would introduce this https://www.drupal.org/project/jsonapi/issues/2956414

Seems like it would be possible with new resource type. 

My idea would be figure who to expose just the basefields for filtering, sorting. 
So you could still search by title, type, date, etc.

**Comment by dawehner** [comment]
What confuses me personally is the following: Entity queue is totally able to handle cross bundle queries.

**Comment by tedbow** [comment]
This https://www.drupal.org/project/entityqueue or \Drupal\Core\Config\Entity\Query\Query ?

Assuming the 2nd. Yeah I think it is more design decision for entity api.
